# Generated by Django 5.0.4 on 2024-07-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDeveloperAssignmentApp', '0003_delete_person_alter_historicalperformance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor_Model',
        ),
    ]
