# Generated by Django 5.0.4 on 2024-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDeveloperAssignmentApp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stream_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'LiveStream_Table',
            },
        ),
    ]
